name: myenv  # Name of your environment
channels:
  - defaults
dependencies:
  - python
  - pip  # Ensure pip is included
  - matplotlib
  - pip:
    - ultralytics  # Packages not available via Conda, to be installed via pip
    - roboflow